version: '3'
services:

  consumer:
    build: React
    command: 'python3 -u app/consumer.py'
    depends_on:
      - react
  react:
    build: React
    ports:
      - 8002:8002
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
  # user:
  #   build: User
  #   ports:
  #     - 8000:8000
  post:
    build: Post
    ports:
      - 8001:8001
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001