version: '3'
services:

  react_db:
    container_name: react_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=react_db

  react_consumer:
    build: React
    restart: always
    volumes:
      - ./React:/React
    command: 'python3 -u app/consumer.py'
    depends_on:
      - react_db

  react:
    build: React
    restart: always
    depends_on:
      - react_db
    volumes:
      - ./React:/React
    ports:
      - 8002:8002
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"



  post_db:
    container_name: post_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=post_db
    
  post_consumer:
    build: Post
    restart: always
    volumes:
      - ./Post:/Post
    command: 'python3 -u app/consumer.py'
    depends_on:
      - post_db

  post:
    build: Post
    restart: always
    depends_on:
      - post_db
    volumes:
      - ./Post:/Post
    ports:
      - 8001:8001
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"


  comment_db:
    container_name: comment_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=comment_db
    
  comment_consumer:
    build: Comment
    restart: always
    volumes:
      - ./Comment:/Comment
    command: 'python3 -u app/consumer.py'
    depends_on:
      - comment_db

  comment:
    build: Comment
    restart: always
    depends_on:
      - comment_db
    volumes:
      - ./Comment:/Comment
    ports:
      - 8003:8003
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"

  
  timeline_db:
    container_name: timeline_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=timeline_db
    
  timeline_consumer:
    build: Timeline
    restart: always
    volumes:
      - ./Timeline:/Timeline
    command: 'python3 -u app/consumer.py'
    depends_on:
      - timeline_db

  timeline:
    build: Timeline
    restart: always
    depends_on:
      - timeline_db
    volumes:
      - ./Timeline:/Timeline
    ports:
      - 8004:8004
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload"


  user_db:
    container_name: user_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_db
    
  user:
    container_name: User
    build: User
    restart: always
    ports:
      - 8010:8010
    volumes:
      - ./User:/User
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload"
    depends_on:
      - user_db

  

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=nkskl6@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - user_db
      - post_db
      - react_db
      - comment_db


  frontend:
    container_name: Frontend
    build: Frontend
    restart: always
    ports:
      - 4200:80
    depends_on:
      - user
      - post
      - react
      - comment
      - timeline