version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  react:
    depends_on:
      - rabbitmq
    build: React
    ports:
      - 8002:8002
  # user:
  #   build: User
  #   ports:
  #     - 8000:8000
  # post:
  #   depends_on:
  #     - rabbitmq
  #   build: Post
  #   ports:
  #     - 8001:8001
  