version: '3'
services:

  command_db:
    container_name: command_db
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=skhan
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=command_db_adda_ghor
  
  query_db:
    container_name: query_db
    image: postgres
    restart: always
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER=skhan
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=query_db_adda_ghor

  command_service:
    container_name: command_service
    build: Backend/command_service
    restart: always
    volumes:
      - Backend_command_service:/app:ro
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_USER=skhan
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=command_db_adda_ghor
    depends_on:
      - command_db
  
  query_service:
    container_name: query_service
    build: Backend/query_service
    restart: always
    volumes:
      - Backend_query_service:/app:ro
    ports:
      - 8001:8000
    command: bash -c "python3 manage.py migrate && python3 script.py"
    environment:
      - POSTGRES_USER=skhan
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=query_db_adda_ghor
    depends_on:
      - query_db

  # frontend:
  #   container_name: frontend
  #   build: Frontend
  #   restart: always
  #   ports:
  #     - 4200:80
  #   depends_on:
  #     - backend

volumes:
  Backend_command_service:
  Backend_query_service: