version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  
  react:
    depends_on:
      - rabbitmq
    build: React
    ports:
      - 8002:8002
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      - PYTHONPATH=/react
  # user:
  #   build: User
  #   ports:
  #     - 8000:8000
  post:
    depends_on:
      - rabbitmq
    build: Post
    ports:
      - 8001:8001
    environment:
      - PYTHONPATH=/post
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

  consumer:
    build: React
    command: 'python3 app/consumer.py'
    depends_on:
      - react
    environment:
      - PYTHONPATH=/react
  