version: '3'
services:

  react_db:
    container_name: react_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=react_db

  react-consumer:
    build: React
    restart: always
    volumes:
      - .:/react
    command: 'python3 -u app/consumer.py'
    depends_on:
      - react_db

  react:
    build: React
    restart: always
    depends_on:
      - react_db
    volumes:
      - .:/react
    ports:
      - 8002:8002
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"



  post_db:
    container_name: post_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=post_db
    
  post-consumer:
    build: Post
    restart: always
    volumes:
      - .:/post
    command: 'python3 -u app/consumer.py'
    depends_on:
      - post_db

  post:
    build: Post
    restart: always
    depends_on:
      - post_db
    volumes:
      - .:/post
    ports:
      - 8001:8001
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"



  user_db:
    container_name: user_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_db
    
  user:
    container_name: User
    build: User
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/user
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - user_db

  

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=nkskl6@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - user_db
      - post_db
      - react_db